server:
  port: 21090
  servlet:
    # 接口前缀配置
    context-path: /api/health-management
# MySQL配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # useSSL=false:禁用SSL加密链接，若数据库在公网或需要高安全性，建议启用SSL并配置证书
    # serverTimezone=GMT%2B8:设置数据库连接的时区为GMT+8（东八区）
    # allowPublicKeyRetrieval=true:允许客户端从服务器获取公钥
    url: jdbc:mysql://localhost:3306/personal_health?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password:
  main:
    # 允许Spring Boot在启动时覆盖已有的Bean定义，涉及到Shiro JwtRealm的使用
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    # Redis启动后，默认提供16个数据库，这里的0表示：使用0号数据库
    database: 0
#    password:XXX
    jedis:
      # Redis连接池配置
      pool:
        # 最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
# 指定MyBatis扫描的Mapper XML文件路径，以实现SQL映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true  # 启用二级缓存
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启SQL日志
jwt:
  secret-key: "d8c986df-8512-42b5-906f-eeea9b3acf86"  # JWT 密钥
  expiration-time: 604800000  # JWT 有效期（7 天，单位：毫秒）
# 文件存储配置
file:
  local-path: E:/myProject/personl-health-management/file/  # 本地存储路径
  url-prefix: /file/  # 对外暴露的URL前缀
# 指定定静态资源的存放路径
resources:
  static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.url-prefix}
